---
collections:
  - name: community.general
    version: 9.4.0
  - name: community.sops
    version: 1.8.2
  - name: ansible.posix
    version: 1.5.4
roles:
  - src: xanmanning.k3s
    version: v3.4.4
