---
collections:
  - name: community.general
    version: 9.4.0
  - name: community.sops
    version: 1.9.1
  - name: ansible.posix
    version: 1.6.0
roles:
  - src: xanmanning.k3s
    version: v3.4.4
