---
collections:
  - name: community.general
    version: 9.5.0
  - name: community.sops
    version: 2.0.0
  - name: ansible.posix
    version: 1.6.2
roles:
  - src: xanmanning.k3s
    version: v3.4.4
