# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-ldap-toml
    namespace: monitoring
stringData:
    ldap-toml: ENC[AES256_GCM,data:HfuEkeS/24TfWYlrUT/hwgs8S1nyRiB/2kulE0U3oQSEzvMwfthOGcHaTDzjKKJQOBjkknyy0tnIKVZp5YgtBiHDBsiRhQXHLrBNwqHzeIwp1GQiAPV7xLI4cQajrFwBAF3MgHGz+mwMwboCNKaYpFy4VAX0tppFARtFbXGoosKPtwvx4dxPdz/gXMdCdd3szlPMEjo4rqXLF4Yppe9c77EGvIshT0OQL8gUn8Vv+3ahjBIpGXpDnqRIH+HHWc8v4HaZj0yQFAoun/czSGTEOeFjAwViJAK0kxNLeKySsgvYmwtKbPBzQIy4ABIkLTM/+A+ehJULE/VgYLVkQtwJ8U+OgB/f4Mc++F8HI1x5n0ur9OU6Wl4qWN8GGqKvH8FB+Q6GTJYx6JMs6lSmnu6ks5w9Sbnp/nIVdUczbINPQkki7mm4l1ejblprbWJu5M5J/NmiJtIr0dsE4fQi4LzSrUQo8i01E8HF/seqYvxGe54Y5N+qtwyBsddrdZHuCH6GH6vxEhTa8UA1hdrE38S58Qm7sMKMmGnTg952lBUS/3Xx2Ag7UklRpB9U8q4vz4OGp1aUiWTESU8GJu7a+CwZPxKt08lxvQDnJ65md/gx6hik+ApPzgl77PFZmxqqna8TgxKmmkbXsJI9cT5NUaJW6KdfCL541pAmO4FdxgqjjYep/YZePg36pV9+QarYyI2/86Lv0K3xJql5fBarOS3ix2mnabgJQpC9TDha01Kh25PqD7FvnjgOtDg3Xoks/AOwUh0qAE7DLx3BC8jCmdu9+FGYKfQwKe0MQLzn3uFfMdUZpP58P+vkqPOP78n0GcRqn5EvJCHM8EM1jHHmvnvk4mEQx0d4AWsyRAvmE6bddmBdXEw0bkdMmnj0yv9m3ImLzZqrNDJ+hPTx6QovPmEq5qPIEYyv4PHoAih0f9PRBNnrs8XI51v1cQ+jQCray1XAK5y78PcM9bwEYKS6PDHhzXY+12GujN33mICM44rpwMat4vGs2+qXrz0MLhO6cTgxI/foakkjVgNFgm3Gu6WRzGjDnHLauk80gxcuOJ6o+KICHCrf5to3LfTm7ajSQ7iNCIvdwXaWJDcp7grkiB82Y7eiEba8IXgqJSPas//cfJpvUQpjJC3pFhvA/DwmdrgEg7yqNLAGdrjNPAD4AIPza5oPv1BbdN9PrGe36lcK9LNu7koykB4jhQa0hApLpC+ORz1DtzDZ6uib2SqOkf5Q3s0fzkclqssPre8tb8xksenBxPoL7y0NH4cp8f7OpVOCLiDDv4QHQC/rYPJA9Pa6UtLqxypnArnJ5wnTAyVl4m64Z5ZJLR7COXgpirAv2SChr3f0pP9mWOE9XkogFpM7MpnDc0Cpm7v9cTP/I1zUgoPUU13R/a4MnEDhCKDYzMhua8+a+4XOXeexjuKMVXY+xyI9i/o+fhii3aC8PC77CMYyGC4jp77Unj5/e/3YMXHGOFC87tTuIOL0MlwpZkWMOLba3ANoO06MBLzbbkPl3vkvBM/lX6qEs0dwPyrM2cIo/oxm2XAN6U0DuiV+bQ1UWCaZWwvUICcsqQckl4Zjhp+QDfkMSN7BbCOxpDyV9keWcd+JiuKJ7uOqs/3SWASFzPMPyWjHg+QqG2EU0gveL/eACPajOuaDprPt8hdyLJQPppHrvnar1ReOBKYUzQA8X5r46k1rIwNhfTT82tPZr9D/2E8HQRPJiOfhCEWkFzqCZ81Ukfv1S0mXs58+6s7TqIZZQGa6PDHj5RPPNT/DPCaOS4nG3gYANaNJcvicVtD7jwriVmIrovchG7sIP/Nf/WCQtIRuT/JtZZ6MgRuV8K6w78AmhWW6w0WM4tvmzapiyUib4aJ0Stk5D6mv4yp2H36z4IecG8uUy7dAnCRKXaWzKXCtyBog4jCGYLgV/gP3p8EgPhLnNz2ORR9A9jYnpL+K3ui9dy9CbyvJ4VVU6bymqei1Fwfz/TzeOY54Dgs=,iv:E0ujuJu1Q4ddyfrPs/dFVLn/9w2M2vRP0BGWgY5Cxr4=,tag:mQMqHocHSkTyK77cZEHi1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2My9pYVpzN0lYbklHendP
            cEFLMmh5NVFma3J0V0VoWWtZUzhwNlJza0dNCk9FbUpJWm83Z2JmSTNBbjBwL3M0
            ZDRRUDRFYUtJUlpCUmtqTzJTNCsrSlUKLS0tIGtSYUtsZGI2d3N2WU5naGJUZ292
            SGlkcTM4Q2lpT3RadzFRUmI4cExKK0EKr0dU3CEy59UEEQC6Yfj+sc0nqKdTqfNb
            mG6Gx3j8E8MWadwl89UmnyYV7D0fUj81GPVG4v64C7bT9tld2sPrUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-31T08:20:38Z"
    mac: ENC[AES256_GCM,data:LJFIhOwj6lqkO4MZN04kAt55Sc4oCiPHSArC+weE4vdY+ovPp3QTDq8OA9Mmh8Zpyn9JyG+32FhfMKfd6sKK9KjHivpueGwRbm5mI8ahQQYqaOh4M5SZ+b1lOvAcC20hJiC12PQr5fpKdKfshmJ/BGQ+o9Et8diHsuU4OYB1FqA=,iv:T7baqWEMcvVXLuK2H+VKOgoWkigyFCGExNqlnO7aif0=,tag:VYwxOvHaN+++sQIl+hnYEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
