# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-ldap-toml
    namespace: monitoring
stringData:
    ldap-toml: |-
        [[servers]]
        # Ldap server host (specify multiple hosts space separated)
        host = "192.168.178.86"
        # Default port is 389 or 636 if use_ssl = true
        port = 636
        # Set to true if ldap server supports TLS
        use_ssl = true
        # Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
        start_tls = false
        # set to true if you want to skip ssl cert validation
        ssl_skip_verify = true

        # Search user bind dn
        bind_dn = "uid=root,cn=users,dc=ldap,dc=fritz,dc=box"
        # Search user bind password
        # If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
        bind_password = 'ztowi9ca9r9roy74'

        # User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
        # Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
        search_filter = "(uid=%s)"

        # An array of base dns to search through
        search_base_dns = ["dc=ldap,dc=fritz,dc=box"]

        group_search_filter = "(&(objectClass=posixAccount)(memberOf=cn=%s,cn=groups,dc=ldap,dc=fritz,dc=box))"
        group_search_filter_user_attribute = "cn"
        group_search_base_dns = ["cn=groups,dc=ldap,dc=fritz,dc=box"]

        # Specify names of the ldap attributes your ldap uses
        [servers.attributes]
        name = "cn"
        surname = "sn"
        username = "cn"
        member_of = "dn"
        email =  "email"

        [[servers.group_mappings]]
        group_dn = "cn=administrators,cn=groups,dc=ldap,dc=fritz,dc=box"
        org_role = "Admin"
        grafana_admin = true
