# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-ldap-toml
    namespace: monitoring
stringData:
    ldap-toml: ENC[AES256_GCM,data:uJKT58VJ1Piewwe45rAbzJxlq2Pua+qiO3QcrzCJbJQ3Wjn3fT1WE2L7Xe2Nu4M98FBUq5W0OEXtuRtaz+GH3TUVrzyIb3epOWAn49+7xaXZUz7q2gh+ioUKXoeDACEi4htAaZg4IgiIXx2WVgS3q9wqy4+EL3JHGA3/nQBBQrBROGSqM5yGVSzwAJNdXt1F9H+2+jW71iHvl68UvVnAf88MDLuVe3ebcUlFrLAD7UzMbePmATL1VU20YUv+CHWJe5rItE+gt1Y1B3mlTY579eJHlPdYhq99w+fkBR+eBwOmc32/+cSYy2jN3yjQpsQ+U3MjsiLxi6maJl4wdeYVSADunFimi4EXOpfQs3uxAYKOATT+KIJZqtJGqh446eS5KG1jHy6z4LOcO8WVph4xi7wRZssCO9UXZCqOiR9axSiBKVRPAJFaMm77yrDpP/Mzl6AeRGTFonPHI4YXrOHgPpoChsocPZ3efjf0adVJmWzjudHWaikDJu2t23TV2D0t4nKzGyALDQjllaoJLbxkqUG7qJCBokQ1rd/lKhbuK8rG5F3OzhEXvibFA9x/jTB8Lpxw6UK20YsiRnM7s2Oa3ErtJegmxUTQHBUnmuK4otYQb/Gh6kOfSYc9lD18g5iVRwvKLxs8U35JD4ICXUN1v66Y4Ljk3TaGS9Lx73uqdQS588kyBNJnXD16Gn4fOgXlQsXCZ2wu1gGGbxAlOUgZ0Za20QQGPfp1xzxsJM1ZiXRj71t20kX6+Y3eNK/GA8PUfETpubEL35jCF0Oav/AB2mdiKTL8KU46sh3tiMTK9xUQrAiU4hyqrN0LXBdCL4Za47NOpwFoqpsZEVslEaelVVNmGjETVHoma5vuOwmngfWXUNDu26Vbo0/LmhkFaW0RZ4sJnopn2zjj2ZKZ1UPIpbB0H87p/Shf0lCmZABT/fGHlVViRBFoJhcCXO7YHuk4qxuTqKTtkYr4aidZSOnfdqVAj5PIktvJSbuSQGqzQj2IbmU/Es+g8u26qWxH1OQoU6BlLXN92yzH13mPZNpPflbnJi9RHJCdZQTgkFdeJK4iuWp4Wr5cPmUUZYp0kCM546wYcDqCOKQPA2uv6bjqQWkUIX+ialpI7cvUMH1tKJaY48CvbQDZoMgSni/L4O3fvblMpPUU//AZH1Veze8JhxnGJJd+y7LMNm/zkxW/ECxjoElNbL71/gxy6/pS/ncQnx6kV32hNsh/yN+Pq5O6WoU/WQledrNcEPcvqVmvXWOEXIFUJJe6sndGtgEG7xSYA0ufolkoYZw4y6CeoxE0ZQQwLzcIKdA8ilxdF4x5m/jywVI7h2y7F/LCVCdnMcIo9iM8myHgh42KFpT9eKIy8V+eIq5ZpkXFi4n1YU9ioqGMZiyWmbejh4IUMYb9CwYKq89JDhcSUio+gZRzyWNxhjKDw8hgtvekJb+g+7mRWiDS58sXgRspZi+KQPsJCCxlZ5H6YfCenF6PwUmVlOee7Vkc5V934ujhVzDUALezkHhK9yCMyRbxTVGf/aSYqwTDcxjO74Tx5EAiO5iGeTmvkgIjHcX+VrOEwM1wO6G/7W+n8seyvuweRAx3BHUg7Eg8hMH4cYMWs27Ho+cRf8YKq5pCtLZ0al6ZMHuNpeFpmftW7w1pL1j6+ir3pVC8jUaL2XS0OGcaMtRvi+ym5FlphFYpXqv8F6aXp1AdAxXsyK0Z+PXIoxQ60AO+bFwm/3l858xFXPW26W6SJQYNMGhwMFbrv2N5AwwulbHSWAEfaczWVHPdWBMHE9Q7QSQa5cWs1lyhYGjPByyZqJt5peA+Or+tRKCKJFWz7v8tZMPFeoBUY8WJGuzSmIwEiKKZHtbX1u9SK6Sq2XqVm8LwGnFlj7mq2sPSBZFafqU9M4IZJ369WbpA5fZdJQTXjWDbhv/HahnkmKI0vUrWpJJPSosl/3atSGAEd1LM9ftxTkKlwrA6Yq7RU4ZrrH7GgfLCMQ6bGeA6lx7kKQ==,iv:uvKbiRNWuMVgmGVrg3g+4lipd50YSs9itQ62VQrWrrM=,tag:cZXjlC+ymeNZG/wWx7dtUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBueVZqYUVjZENrMm52Rlkv
            aUZKUm9TSDdLWERia0t1VzkycWFWampPTFdnCm5NZzd5cnF4T0J1dGNUcC9XVWNm
            WFhLY3VLTzlTRXc3OFNGQ1R5c1k4Z1EKLS0tIFFUWDRQVEQyWFZ0L2srT3NiOWxj
            VmVnN1RKcUkyT1FWR0hUSnkxVlp4ZXMKf87mTujc57kZbcrFHXKYW8HAx/LqF3JP
            UzvPz8F2hT3JbxuG3L9w/KU2C14uMrq0AyUD6WE1AWVuDkR1QRtI5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-05T19:29:52Z"
    mac: ENC[AES256_GCM,data:SRtP/jcc33o3gHYVJdDinoNndCmCCz+qPB9B2KMf3eTzfCs//z64YmptB0fGpmwvpWvYFG+Fs0g18K1B7FnkTnmiQWp0faR40dZmhNB0acb8LFiri+VH+DnodTSE+s+2ZqEfuXsO7eD6sxoHwVoGLlbVVDAFniPGOcoMJLZMwOU=,iv:qB7Q+0Wg5mmF33v7vcdYN9FWWKrX4XAcAJJOi5ca7nU=,tag:kDl0IjSXgGiFxg4lFlqE4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
