# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-ldap-toml
    namespace: monitoring
stringData:
    ldap-toml: ENC[AES256_GCM,data:WoWVcNFlDEDipaqhvWvD6rWfsLiKAvvGDjYiuaOb+U6g80m4pQJcQhPZN33NtcvdLVXsSUZIoYCmAxIa/Z3McTbU7o3VX0pkYBiMEGvXXCuOkhtD7Vxm3PkUaivrsUn0H3I2QGkF23tELkQhkGSCge9XfAlHsOn9RHozprqIKzOW0dSIuFEJwyrcTu14mW+Vb2X1aEfCMAK3txRumAQdc7fIbcsgDxIrQfhtQMiwlZBIwloy2zTKc6fMbSzYfgyIGcrl4lmDHugKpdFP5BGPfy71MSehRsZZNsXA2uUlMAYYN1UV0JX49KQY4ENs+ofF0778OFrvyG8yh59m0FcQxJijMDwE8f9EXpdk9RjG+8KhnH9JYq3W9xdPX+q33fkI+be6h5wMt08N1/UUOz4eC338pOIhrqe0fAqLPhhwM/2zsAy3Ko4UNxKYKfyjgWqXLHziqaiEHKpn7tW1SdsS5SymIiSi2riRIo4KpWhE/qCpXsuTJrVpZHpWaSeAuzLriHBBul7t+BjITXf0xmbbUpL78gJfnHaBmVrcbLOJ7q+1STjU6AN7pxr95u2JK6wV4Bp+aQWgdBfJmAP8UJM3fx/ARhy8GM2johqG99+a+R26bl5KWk6pdr1k8EO0yb6aAF0XlWw2jfQgfLS+w94nRMQCXi0/OZwueQW8me+cwkr+oN8LhwJEstKBBVP6W0FhflEeB5V2T9TEIxwSD5tzLb8PBtLXe1HGGGiT/JO50jSEnH5X+5ywBFD1KUOzzXSDJeekW1miyR/AcieB4qY6wkfhU6Pbni5PEKhMfCnAjv51EAuWMgfMtpnKi3RFHZbdQJVYNUjARo2iRmDz8FF70W6hdzBaqTMt6NQoNMWW+fBXwYdC7PoRrgjrrjjpY6JwifVXaaaHunJpjWkxmgqNlMO5EkV3p4ebfxLcDgLlOHxiKgJ/IX+NnIyVfm9cGOeETVXCIz2rlKpBzyA5+xzoFjkGORG9TZ2e5+vP3twvJAoGFSBk/viwacDUWYmGdUcekGcz3jyVGeJ0sSSAsNluyVK5Spds/8a9RiXwpEs7Op48f0zcKmyEkBormAC1L6vlP1SacISQW1MGLRmpjI+SkSK/EtdLcvpRceM6xMyzARw4v9sq+9l18fCxKDych6A7BHKWOh7IDymOva4GrGck+a6TpVxGOuVvbsfnPvztmLQ8cGIulogJzmb+csn6HDxcHkR85orwzH5R4SX6A+hcRj1az9ytfbSM1hr3ryPQeX+HiX7IjSaFkqHEMeiHUY2Lh6hZDfqs8SxGIosq92SRbC/f2X6BPsN/IAy9AAoc1u+2QlSECKulAi5MU9oupQ64fL+K77Dl0BjNCuACmYKFGMI43MZMdFrD8q6gVMRuBwmvfla0CctHwCJfEM8AAYFmeN41HY0FbH7De9orCqLOBnms6GN2uNBlPR9fhGUcPX1gO1aiqshzKZasLf4eRW4+jLWxdC1dukLD1tMlPORmT/87JndBTrx+XjzYDj6tiQOqKa7ia9onv2ESrxac0XKPWXhnfAXvM81UOQiX7Jk4qfLtPWtqu3AtMLe7qqDcSbMCjH9I2YRz6URB77CTNbuKWDTaaV1d1Afuh3Qvc1KE9B9wcn2kgmwp1T5JBkKO3DCSyVCifiX3rbjS2FimdiN/V7nFAT6Fu9rcBmA+3FABDwFR/kisqAkUjwYvgNy/wN6JtT7i7fpiOfzs9Gf5veEaHQtG+z27YARwyQh7KS27tbUhFGFn/MyDnC8U9JMPVWLJlfmc8wEwtFCl7tFwvrONWHqi1Yr/FUHdV9XEXYr+saPNiIjwt1wp2tprZbrFpRbjc/EK0PbUXj1Vjbm3jI/V3hnUncZX4Ag++te/TghecL0k2whRJJKdbrEb84xwVn701XaDA5Xolw8Jw865rwD0Ok3IsbYMYXpnNA==,iv:wXNwQDSjnqvrcjlcaedfYfdaOU5q1nQVYkabUmkDshs=,tag:18nBnga6i+BWMehCi2b3Qw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuNW9Kejd6aXFDTEFqQUpU
            bDUwSmxWOGczSzQrT3FFd0hXWE8vVmdvWmgwCmxyL0NKU3lQK2RtcXZwNW9LQ0VN
            NVFXSkgwOVdFNHI0TlJtTFNGSk1KOVEKLS0tIFdUbGc4SmZpYXpsZTd4ZWhDcjNN
            V3RHeE1BaDZwaHNab283aUkweFlHR2MKs6iJjmoKsT5LtzAjmXp2hTyyXfyFxW3K
            jog6PaX6XL9L62fWH9FVBZqw8E3TJ3KVNuVObjCb5Ql6TZa26Wvtrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-05T18:57:04Z"
    mac: ENC[AES256_GCM,data:Or9DO9PwGnTxd6tvYkouwAyoXyW0Yg3p2Kjt9f8osf1vUNgQf0L31g4RsmyO4xU3WHneiIW4jjkglsYs7kPFeWbIYG2g7hwjaWxTcVy6qBAd5WEAFDZRqPEr7LNXhRPV6ewuUYn2NqlODETVF6Dab11BSGxpWiRw5YcmNUFLbYA=,iv:0NO5X9kheaSSVAiDtdLljj9RDp0cPOv0bzFzwWSMO68=,tag:0MavIuQnL4epssBte1PpkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
