# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: argocd-secret
    namespace: argocd
    labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
        app.kubernetes.io/managed-by: Helm
    annotations:
        meta.helm.sh/release-namespace: argocd
        meta.helm.sh/release-name: argocd
type: Opaque
data:
    #ENC[AES256_GCM,data:7NVCFnAh97YSZKZn632xX379sfjmA2C3MZVHVW1xnoGik9K9JrZNdz9k8crh6FT8Y3fpw1BhyWRVFqo=,iv:dRk1cZX/zdmCf+S784ZDaz4qwjSdcWaEGb/M9qChruE=,tag:oqXqQbEIJayDBoIgVmHbdQ==,type:comment]
    #ENC[AES256_GCM,data:7AnVmqOexCgPwnRxJmQOVKr6gdG7oQb2fcPZPDKtOpJPLRt/79btMurK8aYKSYN7ubOSxqNTYhWP3rYFIeS0Ptu0dCsiU+l2K/5gowQtLA==,iv:FLf/Xqx368oeTarA4OgeYyn0RA70mvXqKJB+L0qR/fY=,tag:L/VkWeBLDInGfCpfcMCYcA==,type:comment]
    #ENC[AES256_GCM,data:to+G/fSz3wBB,iv:WjhJfFerbfMndvLBQB8bq1uptJZr145wvusOqfMeJmE=,tag:hoY6djEEnnFV4iyARjEG4A==,type:comment]
    #ENC[AES256_GCM,data:P78MP56g267S,iv:369vbnNqsmVFd3RCURDXAnJu8V9U2U3EgjzNgQQa1lI=,tag:q6xoIRCIKtcXLktChHFO3A==,type:comment]
    #ENC[AES256_GCM,data:rrA9TVMrkQLRiRge+FSjcUum5hwPKRLQNDz14eSgmTjXx3+v24RLq8zydDXx836HwmJ44EtNohfgrK2F05vRl2eAXmF28cqXLQ==,iv:4Hh9McQ9MEWYbYiTDAerTJuetjVmWFpEYMSkV+1h2+0=,tag:UScCWen/XkdJ7XCV30oEoA==,type:comment]
    #ENC[AES256_GCM,data:6GBqcDPkkwnx8FkWmdzIKCLDF3HYoYNrw+LqMxCgcMtE3BUnObuRUFPayVfXHAvxSdK83DYmiESm3mT1nx3a8pL2hsk=,iv:cKc4QK7R3HklN7nkeJoMAg9TcrO2wV9Ju2GY+BURqJE=,tag:fe6qS94FuZPv1V7CE7O0Bw==,type:comment]
    #ENC[AES256_GCM,data:pF8rh3HmyVBy9qLFRrRCsp7Wp31IB96esHpn2Rk9bpWbrwss252+SJD/4uPg4dteBvI+2INECJ4JEy0uyH5KLwCIgAR2KmXN5MlTaz6BUrPjfGSzrnjj+phA4WBcLnuI3LOH23jHYpuuzpWaAkptNQ4=,iv:L9FYhhK73vStaq7DD8a0E/+TqVbzeafjFeTapZre36M=,tag:QcXFGVkKJa017S5aqWIbOg==,type:comment]
    admin.password: ENC[AES256_GCM,data:PCfP4LpYWYjnJry7yl5ZLtecdiXVBfwNQJH2Yrpq22gdRiD7SpRtJKcZnIOMsaLydHsYtTpnWy7hyMxp,iv:on48okY7hDGwjmzRHo+vpBP8oXr/3Su8xTmoIDE0fB8=,tag:FN/SK2VS5QiGn3TqWwItWQ==,type:str]
    #ENC[AES256_GCM,data:jmkHwvDEZa4VxUMglmWp3bYZ+j1ktmCv8Iqya35W/JsJs97BsecGPMVCEZnHo0YCiEmuU4WvilDdmHxG9cJc,iv:4qeft2Z/qFcHpIr1OiPPNODdegiPgPGxXY87DFh4B6g=,tag:R669ATsM0OdTfDWc/veC+g==,type:comment]
    #ENC[AES256_GCM,data:lQJWbYbiWiWmJg9INDa2plPXn5H+iQ+DacSv5w==,iv:77WFWBfFdjDfMhvrt8ioJBg8quk0PHPND7UlHqELGvQ=,tag:PSp/Ox/uav3s49tRFDOM6A==,type:comment]
    #ENC[AES256_GCM,data:b48gBzloeQYoLsD3qMz6QH5c,iv:lZ+hEFAsEQB84KQQ/Mafz18AZMU2T03Z6ukyRc78wQE=,tag:qjRLnZDls8miB16dXRc6vg==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdWhWUlBwV2xDYndtQ2pv
            RWEzUUc2NDhQc0FiUE45alFNbStIQUdkK1JvCmZhdkVJVVZFYVovbDdkNktOcjhl
            SmdhRVNOQ1JkV2RsOVM0ZW5hSTI5cTAKLS0tIEFwZXdxdm1EOThjVnIwQk96SDJt
            dTdkMFZOdHVRaDJTYXp4SWN5MXJxNzgKRWh5B163pn+SWInxdyT4oHcQ27bzXOx5
            8vgMVic8f7TU0bJmvFkDfkQrXS/5JDsh7rQZiS7BneZODfd49OSLvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T11:52:11Z"
    mac: ENC[AES256_GCM,data:3nAZxg9GNTd9bSV929i2GlR5zFIFLCyCWNzhynyde0VSB0xkGwQqiD2XI3vDz+SG0ePtMg9KuKsu8KxOE1SnNvneOQTq5PExIfYAGtE9HpmS7tLZJOpmez/1fLhlwqK05RqaLZBetHjHFcnLyOWEQ3HbT6o9ziUnjZGNdWeKS7w=,iv:r7iR33cEv391nTCrbTdJArKdwLQnEIbkWkJhp6GpMXU=,tag:63B4hgP7xVXNjtzPNfIZ4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
---
apiVersion: v1
kind: Secret
metadata:
    name: github-https-creds
    namespace: argocd
    labels:
        argocd.argoproj.io/secret-type: repo-creds
stringData:
    url: ENC[AES256_GCM,data:a8zEeCTmpNCrMev2YT++aeg/kLUydS4uDA==,iv:Jxigkv9bGXAr+px4mKB53IuJDHgBtf4/zEjZCR6NmaM=,tag:dj/L0ql/AFFilZ6EVRrDNg==,type:str]
    type: ENC[AES256_GCM,data:s8D3BQ==,iv:Dc9wU3z3pxTGcpGnRiPxaHP4L2KWarRaWZS2uOfD+G4=,tag:B+1WkZHE1g5WxVLGOqOFBQ==,type:str]
    password: ENC[AES256_GCM,data:vSbckhGjNbmMK976r/qWFA==,iv:YRDeXwOUoHswsdv8psaX+fqDOGsV87bGbu96uzbJEKY=,tag:et0QX2hbJ9JSVHfS1A8xpw==,type:str]
    username: ENC[AES256_GCM,data:DcDTbULy,iv:yFnjUflciHl/m3da+hYK10VoV7JF69VqBYc20lDKz+E=,tag:zNLH9Qy8gj2CRzb0LN9fuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTdWhWUlBwV2xDYndtQ2pv
            RWEzUUc2NDhQc0FiUE45alFNbStIQUdkK1JvCmZhdkVJVVZFYVovbDdkNktOcjhl
            SmdhRVNOQ1JkV2RsOVM0ZW5hSTI5cTAKLS0tIEFwZXdxdm1EOThjVnIwQk96SDJt
            dTdkMFZOdHVRaDJTYXp4SWN5MXJxNzgKRWh5B163pn+SWInxdyT4oHcQ27bzXOx5
            8vgMVic8f7TU0bJmvFkDfkQrXS/5JDsh7rQZiS7BneZODfd49OSLvw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T11:52:11Z"
    mac: ENC[AES256_GCM,data:3nAZxg9GNTd9bSV929i2GlR5zFIFLCyCWNzhynyde0VSB0xkGwQqiD2XI3vDz+SG0ePtMg9KuKsu8KxOE1SnNvneOQTq5PExIfYAGtE9HpmS7tLZJOpmez/1fLhlwqK05RqaLZBetHjHFcnLyOWEQ3HbT6o9ziUnjZGNdWeKS7w=,iv:r7iR33cEv391nTCrbTdJArKdwLQnEIbkWkJhp6GpMXU=,tag:63B4hgP7xVXNjtzPNfIZ4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
