---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: argocd
  namespace: argocd
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://argoproj.github.io/argo-helm/
      chart: argo-cd
      version: 5.36.0
      sourceRef:
        kind: HelmRepository
        name: argocd-charts
        namespace: flux-system
      interval: 5m
  values:
    global:
      image:
        # -- If defined, a repository applied to all Argo CD deployments
        repository: quay.io/argoproj/argocd
        # -- Overrides the global Argo CD image tag whose default is the chart appVersion
        tag: "v2.7.4"
        # -- If defined, a imagePullPolicy applied to all Argo CD deployments
        imagePullPolicy: IfNotPresent

      networkPolicy:
        # -- Create NetworkPolicy objects for all components
        create: false
        # -- Default deny all ingress traffic
        defaultDenyIngress: false
    ## Controller
    controller:
      # -- Application controller name string
      name: application-controller

      # -- The number of application controller pods to run.
      # If changing the number of replicas you must pass the number as `ARGOCD_CONTROLLER_REPLICAS` as an environment variable
      replicas: 1

      # -- Deploy the application controller as a StatefulSet instead of a Deployment, this is required for HA capability.
      enableStatefulSet: true

      # -- Resource limits and requests for the application controller pods
      resources:
        requests:
          cpu: 150m
          memory: 250Mi
        limits:
          memory: 400MI

      ## Application controller metrics configuration
      metrics:
        # -- Deploy metrics service
        enabled: true

        serviceMonitor:
          # -- Enable a prometheus ServiceMonitor
          enabled: true

        rules:
          # -- Deploy a PrometheusRule for the application controller
          enabled: true
          # -- PrometheusRule.Spec for the application controller
          spec:
            - alert: ArgoAppNotSynced
              expr: |
                argocd_app_info{sync_status!="Synced"} == 1
              for: 1h
              labels:
                severity: warning
              annotations:
                summary: "Application {{ $labels.name }} not synchronized"
                description: >
                  The application {{ $labels.name }} has not been synchronized for over
                  1 hour which means that the state of this cloud has drifted away from the
                  state inside Git.
            - alert: ArgoAppNotHealthy
              expr: |
                argocd_app_info{health_status!="Healthy"} == 1
              for: 15m
              labels:
                severity: critical
              annotations:
                summary: "Application {{ $labels.name }} not healthy"
                description: >
                  The application {{ $labels.name }} has not been healthy for over
                  15 minutes.
          selector:
            prometheus: kube-prometheus-stack
          namespace: monitoring

      ## Enable if you would like to grant rights to Argo CD to deploy to the local Kubernetes cluster.
      clusterAdminAccess:
        # -- Enable RBAC for local cluster deployments
        enabled: true

    ## Dex
    dex:
      # -- Enable dex
      enabled: true
      # -- Dex name
      name: dex-server

      # # -- Additional volumeMounts to the dex main container
      # volumeMounts:
      #   - name: static-files
      #     mountPath: /shared

      # # -- Additional volumes to the dex pod
      # volumes:
      #   - name: static-files
      #     emptyDir: {}

      # -- Resource limits and requests for dex
      resources:
        requests:
          cpu: 8m
          memory: 32Mi
        limits:
          memory: 128Mi

    ## Redis
    redis:
      # -- Enable redis
      enabled: true
      # -- Redis name
      name: redis

      image:
        # -- Redis repository
        repository: public.ecr.aws/docker/library/redis
        # -- Redis tag
        tag: 7.0.11-alpine
        # -- Redis imagePullPolicy
        imagePullPolicy: IfNotPresent

      # -- Redis pod-level security context
      securityContext:
        runAsNonRoot: true
        runAsUser: 999

      # -- Resource limits and requests for redis
      resources:
        requests:
          cpu: 5m
          memory: 5Mi
        limits:
          memory: 64Mi

      metrics:
        # -- Deploy metrics service and redis-exporter sidecar
        enabled: false

    # This key configures Redis-HA subchart and when enabled (redis-ha.enabled=true)
    # the custom redis deployment is omitted
    # Check the redis-ha chart for more properties
    redis-ha:
      # -- Enables the Redis HA subchart and disables the custom Redis single node deployment
      enabled: false

    ## Server
    server:
      # -- Argo CD server name
      name: argo-cd-server

      # -- Resource limits and requests for the Argo CD server
      resources:
        requests:
          cpu: 7m
          memory: 32Mi
        limits:
          memory: 128Mi

      ## Certificate configuration
      certificate:
        # -- Deploy a Certificate resource (requires cert-manager)
        enabled: true
        # -- Certificate primary domain (commonName)
        domain: "argocd.${SECRET_DOMAIN}"
        # -- The requested 'duration' (i.e. lifetime) of the Certificate. Value must be in units accepted by Go time.ParseDuration
        duration: "2160h"
        # -- How long before the currently issued certificate's expiry cert-manager should renew the certificate. Value must be in units accepted by Go time.ParseDuration
        renewBefore: "336h"
        issuer:
          # -- Certificate issuer group. Set if using an external issuer. Eg. `cert-manager.io`
          group: "cert-manager.io"
          # -- Certificate issuer kind. Either `Issuer` or `ClusterIssuer`
          kind: "ClusterIssuer"
          # -- Certificate isser name. Eg. `letsencrypt`
          name: "letsencrypt-production"
        # -- The name of the Secret that will be automatically created and managed by this Certificate resource
        secretName: argocd-server-tls


      ## Server metrics service configuration
      metrics:
        # -- Deploy metrics service
        enabled: true

        serviceMonitor:
          # -- Enable a prometheus ServiceMonitor
          enabled: true

          selector:
            prometheus: kube-prometheus-stack

      ingress:
        # -- Enable an ingress resource for the Argo CD server
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"        
          hajimari.io/enable: "true"
          hajimari.io/icon: "sitemap"
          hajimari.io/appName: "argocd"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - "argocd.${SECRET_DOMAIN}"
        # -- List of ingress paths
        paths:
          - /
        # -- Ingress path type. One of `Exact`, `Prefix` or `ImplementationSpecific`
        pathType: Prefix
        tls:
          - hosts:
              - "argocd.${SECRET_DOMAIN}"
            secretName: "argocd-tls-secret"
        # -- Uses `server.service.servicePortHttps` instead `server.service.servicePortHttp`
        https: true


    ## Repo Server
    repoServer:
      # -- Repo server name
      name: repo-server
      # -- The number of repo server pods to run
      replicas: 1
      autoscaling:
        # -- Enable Horizontal Pod Autoscaler ([HPA]) for the repo server
        enabled: false

      ##### KSOPS CONFIGURATION #####
      # Set the XDG_CONFIG_HOME env variable to allow kustomize to detect the plugin
      env:
        - name: GNUPGHOME
          value: /home/argocd/.gnupg
        - name: XDG_CONFIG_HOME
          value: /.config
      # Use init containers to configure custom tooling
      # https://argoproj.github.io/argo-cd/operator-manual/custom_tools/
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: gnupg-home
          emptyDir: {}
        - name: deploy-gpg-key
          secret:
            secretName: sops-gpg
      initContainers:
        - name: import-gpg-key
          image: argoproj/argocd:v2.6.9
          command: ["gpg", "--import", "/deploy-gpg-key/sops.asc"]
          env:
            - name: GNUPGHOME
              value: /gnupg-home/.gnupg
          volumeMounts:
            - mountPath: /deploy-gpg-key
              name: deploy-gpg-key
              readOnly: true
            - mountPath: /gnupg-home
              name: gnupg-home      
        - name: install-ksops
          image: viaductoss/ksops:v4.1.1-arm64
          command: ["/bin/sh", "-c"]
          args:
            - echo "Installing KSOPS...";
              mv ksops /custom-tools/;
              mv $GOPATH/bin/kustomize /custom-tools/;
              echo "Done.";
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools
      volumeMounts:
        - mountPath: /home/argocd/.gnupg
          name: gnupg-home
          subPath: .gnupg
        # - name: gpg-private-key
        #   mountPath: /app/config/gpg
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
          # Verify this matches a XDG_CONFIG_HOME=/.config env variable
        - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
          name: custom-tools
          subPath: ksops          

      resources:
        requests:
          cpu: 25m
          memory: 50Mi
        limits:
          memory: 128Mi

        # rbac permssions
      rbac:
      - apiGroups:
        - ""
        resources:
        - secrets
        verbs:
        - get


    applicationSet:
      # -- Enable Application Set controller
      enabled: true

      # -- Application Set controller name string
      name: applicationset-controller

      # -- The number of controller pods to run
      replicaCount: 1

      # -- Resource limits and requests for the controller pods.
      resources:
        requests:
          cpu: 5m
          memory: 40Mi
        limits:
          memory: 80Mi
