---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://mojo2600.github.io/pihole-kubernetes/
      chart: pihole
      version: 2.20.0
      sourceRef:
        kind: HelmRepository
        name: pihole-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system      
  values:
    replicaCount: 1
    maxUnavailable: 0
    image:
      repository: "pihole/pihole"
      tag: "2023.11.0"
      pullPolicy: IfNotPresent
    admin:
      existingSecret: "pihole-secrets"
      passwordKey: "ADMIN_PASSWORD"
    resources:
      requests:
        cpu: 10m
        memory: 90Mi
      limits:
        memory: 160Mi
    # DNS1: "208.67.222.222"
    # #DNS2: "1.1.1.1"
    # DNS2: "2620:119:35::35"
    # #DNS4: "2606:4700:4700::1111"
    extraEnvVars:
      WEBTHEME: default-dark
      WEBUIBOXEDLAYOUT: boxed
      FTLCONF_LOCAL_IPV4: 192.168.178.202
      REV_SERVER: true
      REV_SERVER_TARGET: 192.168.178.1
      REV_SERVER_DOMAIN: fritz.box
      REV_SERVER_CIDR: 192.168.178.0/24
      DNSMASQ_LISTENING: all
      DNS_BOGUS_PRIV: true
      DNS_FQDN_REQUIRED: true
      DNSSEC: false
    ftl:
      MAXDBDAYS: 14      
    adlists:
      - https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
      - https://v.firebog.net/hosts/static/w3kbl.txt
      - https://raw.githubusercontent.com/matomo-org/referrer-spam-blacklist/master/spammers.txt
      - https://someonewhocares.org/hosts/zero/hosts
      - https://raw.githubusercontent.com/VeleSila/yhosts/master/hosts
      - https://winhelp2002.mvps.org/hosts.txt
      - https://v.firebog.net/hosts/neohostsbasic.txt
      - https://raw.githubusercontent.com/RooneyMcNibNug/pihole-stuff/master/SNAFU.txt
      - https://adaway.org/hosts.txt
      - https://v.firebog.net/hosts/AdguardDNS.txt
      - https://v.firebog.net/hosts/Admiral.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
      - https://v.firebog.net/hosts/Easylist.txt
      - https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
      - https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
      - https://raw.githubusercontent.com/jdlingyu/ad-wars/master/hosts
      - https://v.firebog.net/hosts/Easyprivacy.txt
      - https://v.firebog.net/hosts/Prigent-Ads.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
      - https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
      - https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
      - https://www.github.developerdan.com/hosts/lists/ads-and-tracking-extended.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/android-tracking.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
      - https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/AmazonFireTV.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-blocklist.txt 
      - https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
      - https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
      - https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
      - https://v.firebog.net/hosts/Prigent-Crypto.txt
      - https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
      - https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
      - https://phishing.army/download/phishing_army_blocklist_extended.txt
      - https://malware-filter.gitlab.io/malware-filter/phishing-filter-hosts.txt
      - https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
      - https://v.firebog.net/hosts/RPiList-Malware.txt
      - https://v.firebog.net/hosts/RPiList-Phishing.txt
      - https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
      - https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/hosts
      - https://urlhaus.abuse.ch/downloads/hostfile/  
      - https://v.firebog.net/hosts/Prigent-Malware.txt
      - https://raw.githubusercontent.com/anudeepND/blacklist/master/facebook.txt
    whitelist:
      - sentry.io
      - unagi-na.amazon.com
      - app.usercentrics.eu
      - graphql.usercentrics.eu
      - 0.client-channel.google.com
      - 1drv.com
      - 2.android.pool.ntp.org
      - akamaihd.net
      - akamaitechnologies.com
      - akamaized.net
      - amazonaws.com
      - android.clients.google.com
      - api.ipify.org
      - api.rlje.net
      - app-api.ted.com
      - appleid.apple.com
      - apps.skype.com
      - appsbackup-pa.clients6.google.com
      - appsbackup-pa.googleapis.com
      - apt.sonarr.tv
      - aspnetcdn.com
      - attestation.xboxlive.com
      - ax.phobos.apple.com.edgesuite.net
      - brightcove.net
      - c.s-microsoft.com
      - cdn.cloudflare.net
      - cdn.embedly.com
      - cdn.optimizely.com
      - cdn.vidible.tv
      - cdn2.optimizely.com
      - cdn3.optimizely.com
      - cdnjs.cloudflare.com
      - cert.mgt.xboxlive.com
      - clientconfig.passport.net
      - clients1.google.com
      - clients2.google.com
      - clients3.google.com
      - clients4.google.com
      - clients5.google.com
      - clients6.google.com
      - cpms.spop10.ams.plex.bz
      - cpms35.spop10.ams.plex.bz
      - cse.google.com
      - ctldl.windowsupdate.com
      - d2c8v52ll5s99u.cloudfront.net
      - d2gatte9o95jao.cloudfront.net
      - dashboard.plex.tv
      - dataplicity.com
      - def-vef.xboxlive.com
      - delivery.vidible.tv
      - dev.virtualearth.net
      - device.auth.xboxlive.com
      - display.ugc.bazaarvoice.com
      - displaycatalog.mp.microsoft.com
      - dl.delivery.mp.microsoft.com
      - dl.dropbox.com
      - dl.dropboxusercontent.com
      - dns.msftncsi.com
      - download.sonarr.tv
      - drift.com
      - driftt.com
      - dynupdate.no-ip.com
      - ecn.dev.virtualearth.net
      - edge.api.brightcove.com
      - eds.xboxlive.com
      - fonts.gstatic.com
      - forums.sonarr.tv
      - g.live.com
      - geo-prod.do.dsp.mp.microsoft.com
      - geo3.ggpht.com
      - giphy.com
      - github.com
      - github.io
      - googleapis.com
      - gravatar.com
      - gstatic.com
      - help.ui.xboxlive.com
      - hls.ted.com
      - i.ytimg.com
      - i1.ytimg.com
      - imagesak.secureserver.net
      - img.vidible.tv
      - imgix.net
      - imgs.xkcd.com
      - instantmessaging-pa.googleapis.com
      - intercom.io
      - jquery.com
      - jsdelivr.net
      - keystone.mwbsys.com
      - lastfm-img2.akamaized.net
      - licensing.xboxlive.com
      - live.com
      - login.live.com
      - login.microsoftonline.com
      - manifest.googlevideo.com
      - meta-db-worker02.pop.ric.plex.bz
      - meta.plex.bz
      - meta.plex.tv
      - microsoftonline.com
      - msftncsi.com
      - my.plexapp.com
      - nexusrules.officeapps.live.com
      - npr-news.streaming.adswizz.com
      - nine.plugins.plexapp.com
      - no-ip.com
      - node.plexapp.com
      - notify.xboxlive.com
      - ns1.dropbox.com
      - ns2.dropbox.com
      - o1.email.plex.tv
      - o2.sg0.plex.tv
      - ocsp.apple.com
      - office.com
      - office.net
      - office365.com
      - officeclient.microsoft.com
      - om.cbsi.com
      - onedrive.live.com
      - outlook.live.com
      - outlook.office365.com
      - placehold.it
      - placeholdit.imgix.net
      - players.brightcove.net
      - pricelist.skype.com
      - products.office.com
      - proxy.plex.bz
      - proxy.plex.tv
      - proxy02.pop.ord.plex.bz
      - pubsub.plex.bz
      - pubsub.plex.tv
      - raw.githubusercontent.com
      - redirector.googlevideo.com
      - res.cloudinary.com
      - s.gateway.messenger.live.com
      - s.marketwatch.com
      - s.youtube.com
      - s.ytimg.com
      - s1.wp.com
      - s2.youtube.com
      - s3.amazonaws.com
      - sa.symcb.com
      - secure.avangate.com
      - secure.brightcove.com
      - secure.surveymonkey.com
      - services.sonarr.tv
      - skyhook.sonarr.tv
      - spclient.wg.spotify.com
      - ssl.p.jwpcdn.com
      - staging.plex.tv
      - status.plex.tv
      - t.co
      - t0.ssl.ak.dynamic.tiles.virtualearth.net
      - t0.ssl.ak.tiles.virtualearth.net
      - tawk.to
      - tedcdn.com
      - themoviedb.com
      - thetvdb.com
      - tinyurl.com
      - title.auth.xboxlive.com
      - title.mgt.xboxlive.com
      - traffic.libsyn.com
      - tvdb2.plex.tv
      - tvthemes.plexapp.com
      - twimg.com
      - ui.skype.com
      - video-stats.l.google.com
      - videos.vidible.tv
      - widget-cdn.rpxnow.com
      - win10.ipv6.microsoft.com
      - wp.com
      - ws.audioscrobbler.com
      - www.dataplicity.com
      - www.googleapis.com
      - www.msftncsi.com
      - www.no-ip.com
      - www.youtube-nocookie.com
      - xbox.ipv6.microsoft.com
      - xboxexperiencesprod.experimentation.xboxlive.com
      - xflight.xboxlive.com
      - xkms.xboxlive.com
      - xsts.auth.xboxlive.com
      - youtu.be
      - youtube-nocookie.com
      - yt3.ggpht.com
      - zee.cws.conviva.com
      - pings.conviva.com
      - cws.conviva.com
      - livepassdl.conviva.com
      - gfwsl.geforce.com
      - appspot-preview.l.google.com
      - vidtech.cbsinteractive.com
      - continuum.dds.microsoft.com
      - connectivitycheck.gstatic.com
      - connectivitycheck.android.com
      - www.msftconnecttest.com
    # networking config
    serviceDns:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      loadBalancerIP: 192.168.178.202
    privileged: true
    dnsmasq:
      customDnsEntries:
        - address=/nas.${SECRET_DOMAIN}/192.168.178.201
        - address=/alert-manager.${SECRET_DOMAIN}/192.168.178.201
        - address=/grafana.${SECRET_DOMAIN}/192.168.178.201
        - address=/hass.${SECRET_DOMAIN}/192.168.178.201
        - address=/prometheus.${SECRET_DOMAIN}/192.168.178.201
        - address=/rezepte.${SECRET_DOMAIN}/192.168.178.201
        - address=/traefik.${SECRET_DOMAIN}/192.168.178.201
        - address=/start.${SECRET_DOMAIN}/192.168.178.201
        - address=/router.${SECRET_DOMAIN}/192.168.178.201
        - address=/zwave.${SECRET_DOMAIN}/192.168.178.201
        - address=/scraang.${SECRET_DOMAIN}/192.168.178.201
        - address=/scraang-dev.${SECRET_DOMAIN}/192.168.178.201
        - address=/argocd.${SECRET_DOMAIN}/192.168.178.201
        - address=/pihole.${SECRET_DOMAIN}/192.168.178.201
        - address=/weave.${SECRET_DOMAIN}/192.168.178.201
        - address=/miniflux.${SECRET_DOMAIN}/192.168.178.201
        - address=/adguardhome.${SECRET_DOMAIN}/192.168.178.201
        - address=/monica.${SECRET_DOMAIN}/192.168.178.201
        - address=/weave.${SECRET_DOMAIN}/192.168.178.201
    serviceDhcp:
      enabled: false
    persistentVolumeClaim:
      enabled: true
      existingClaim: pihole-pvc
    doh:
      enabled: true
      name: "cloudflared"
      repository: "crazymax/cloudflared"
      tag: "2023.10.0"
      pullPolicy: IfNotPresent
      envVars:
        TUNNEL_DNS_UPSTREAM: "https://1.1.1.2/dns-query,https://1.0.0.2/dns-query"

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: traefik
        hajimari.io/enable: "true"
        hajimari.io/icon: "pihole"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/private-key-secret-name: "root-secret"        
      path: /
      hosts:
        - "pihole.${SECRET_DOMAIN}"
      tls:
        - hosts:
          - "pihole.${SECRET_DOMAIN}"
          secretName: "tls-wildcard-secret"
    monitoring:
      podMonitor:
        enabled: true
      sidecar:
        enabled: false
        port: 9617
        image:
          repository: ekofr/pihole-exporter
          tag: v0.4.0
          pullPolicy: IfNotPresent
        resources:
          requests:
            memory: 14Mi
            cpu: 2m
          limits:
            memory: 32Mi
