---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: firefly-db
  namespace: firefly
spec:
  interval: 5m
  chart:
    spec:
      chart: firefly-db
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: firefly-iii-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system
  values:
    image:
      repository: postgres
      tag: 14-alpine
      pullPolicy: IfNotPresent

    storage:
      class: nfs-client
      accessModes: ReadWriteOnce
      dataSize: 1Gi
      
    backup: {}
    backupSchedule: {}

    configs:
      DBHOST: firefly-firefly-db
      DBPORT: "5432"
      DBNAME: firefly
      DBUSER: firefly
      TZ: Europe/Berlin
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: firefly
        # -- Set this to the name of a secret to load environment variables from. If defined, values in the secret will override values in configs
      existingSecret: "firefly-iii-secrets"
