---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkding
  namespace: linkding
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nliakm.github.io/helm-charts/
      chart: linkding
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: nliakm-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system
  values:
    metadata:
      namespace: linkding

    image:
      repository: sissbruecker/linkding
      tag: 1.36.0-alpine
      pullPolicy: IfNotPresent

    replicaCount: 1

    ingress:
      enabled: true
      className: traefik
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        hajimari.io/enable: "true"
        hajimari.io/icon: bookmark-multiple-outline
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        secretName: tls-wildcard-secret
      hostName: "linkding.${SECRET_DOMAIN}"
      path: /
      pathType: Prefix

    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 300m
        memory: 256Mi

    persistence:
      enabled: true
      accessMode: "ReadWriteOnce"
      storageSize: "1Gi"
      storageClass: "nfs-client"

    database:
      engine: sqlite

    superUser:
      existingSecret: "linkding-superuser"
