apiVersion: v1
kind: Secret
metadata:
    name: linkding-superuser
    namespace: linkding
type: Opaque
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:W1IctHk=,iv:osYt0Mui7WE+MlJsS+crSTtRyX526y35glRp+k8qx00=,tag:dVEv7jmF15ENWIXXTRYWsQ==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:zWHCRbHOVai3yepvS9n+DQ==,iv:/YKApZdlvi1oeWt6cUe8pyvGPc5zkj4TyB+yuqt3uow=,tag:2U6DZjrxmqWgnvbbkIKGLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYeWQvOWxkSnp6U2RlRVBr
            aTdpcFo2Sm1ja1FPZ0s2MXUwYjlqQnhFQUdRCjJJcFVVdEk4RHltZzdibEliSEMz
            NDlIVVcvYyt1eHNGREYvOEQwTHZTbnMKLS0tIE9CWWV0STRKanl0K2dFR0ExbWl4
            YUpGSWdFb1NnejdqOUU3cGl4M1Z0ZGsK10ylGRz49ceoaZ2MnGm/A3zChjMZSo0r
            Etw6YEVnt2G8e66fTCMt1Q9otX6O3FPIluC/vElgDfSD63iox/g/xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-23T09:05:51Z"
    mac: ENC[AES256_GCM,data:XrRCI87z+8CaTHWmirX+iIQsFaW3aZDK1+avmDDDh+neXjKaK06JwVjG6Wey8LF7Sa9Gm2uJbT3J9W0+H63mJb+SOWx96ECeMeQ+yHWpUfSbiXIoI4JGLgzub3ZyMALbaMT5nzCZsCNAK//iepTeo6D+xfN+YdK1v283Rxj3Irw=,iv:1g1y24WTPCl1qm7NqYxdt9qeZNm2vqQMKBKxdVG/i4E=,tag:pqfDzRYLcczmIZPgQQM4kA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
