---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
  values:
    image:
      repository: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner
      tag: v4.0.2
      imagePullPolicy: IfNotPresent
      # namespaceSelector:
      #   matchNames:
      #     - nfs-system
    nfs:
      server: ${NFS_SERVER}
      path: ${NFS_PATH}
      volumeName: nfs-subdir-external-provisioner-root
      reclaimPolicy: Retain
      mountOptions:
        - nfsvers=3
        - nolock
        - soft
        - rw      
    storageClass:
      create: true
      defaultClass: true
      name: nfs-client
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      archiveOnDelete: true
      accessModes: ReadWriteOnce
      annotations: {}
    leaderElection:
      enabled: true
    rbac:
      create: true
    podSecurityPolicy:
      enabled: false
    podAnnotations: {}
    serviceAccount:
      create: true
      annotations: {}
      name:
    resources:
      requests:
        cpu: 5m
        memory: 13Mi
      limits:
        memory: 32Mi
      
    labels: {}
