---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: wger
  namespace: wger
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://nliakm.github.io/helm-charts/
      chart: wger
      version: 0.0.3
      sourceRef:
        kind: HelmRepository
        name: nliakm-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system      
  values:
    app:
      timezone: "Europe/Berlin"
      global:
        replicas: 1
        image:
          PullPolicy: IfNotPresent
      nginx:
        enabled: true
      axes:
        enabled: true
        failureLimit: 10
        # in minutes
        cooloffTime: 30
        # number of reverse proxies involved
        ipwareProxyCount: 1
        # order of magnitude from last proxy for the real ip
        ipwareMetaPrecedenceOrder: "X_FORWARDED_FOR,REMOTE_ADDR"
      persistence:
        enabled: true
        storageClass: "nfs-client"
        sizeMedia: 5Gi
        sizeStatic: 5Gi
        sizeCeleryBeat: 1Gi

    celery:
        enabled: true

    ingress:
      enabled: true
      url: "wger.${SECRET_DOMAIN}"
      tls: true
      annotations:
        kubernetes.io/ingress.class: traefik
        hajimari.io/enable: "true"
        hajimari.io/icon: "dumbbell"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/private-key-secret-name: "root-secret" 

    existingPostgres:
      enabled: true
      existingSecret: postgres-secret

    postgres:
      enabled: false

    redis:
      enabled: true
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi      
      auth:
        enabled: false
      storage:
        className: "nfs-client"
        requestedSize: 1Gi
      service:
        serverPort: 6379  