---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.10
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
  values:
    # controller contains configuration specific to the MetalLB cluster
    # controller.
    controller:
      enabled: true
      logLevel: info
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 32Mi

    speaker:
      enabled: true
      logLevel: info

      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 10m
          memory: 30Mi

      frr:
        enabled: false

    crds:
      enabled: true
      validationFailurePolicy: Fail
