apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - monitoring-secrets.sops.yaml
  - kube-prometheus-stack
  - blackbox-exporter
  - alertmanager-discord
#  - loki
  - grafana