# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: monitoring-secrets
    namespace: monitoring
stringData:
    HOME_ASSISTANT_BEARER: ENC[AES256_GCM,data:mI2TXGyrO6YGVQn4KHGX0trRMLoRamQFDpBtc+Jk18vkT4RYzEgf5a++xG/ld89Z/MjbG1uvbrTCDTplgAwCzr+M3g5yZx6Y4pOJZXyvJ4blS0tEEdqh309qw8kg2yjCJP/wdihighXNzVmQvPz/3uMvKD2M6T6NN8NJF7QiOzIKJrq/rlX0cXYvatW3rWPJ2KY56Nqa9QteZRk4TCvt75N7oGvYSVkLTx1nhE6p+TEwwZNAiuPi,iv:PBj2W/XlbiMUotAI4KKce2nA/iqyngrv4hXCVIH3oLo=,tag:JOainJlOKxJyPSuBAtvmnQ==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:+RWHqDbIsVrcGdk/bu3Hoz+0xJ72AlueszMQFBKc3mcpu/mG3od50nlM0Czmmz2Hr6/ZyQnf3L6f626Eh7WAdE11Qx8u6DvZwYgROReRtB7ayTHSMHdGWKLwRaya0LB7xx4OnX8WqABrKo2jz4G9fkuT5txsFFuJ,iv:splGvHWZHgkwYYmaoSdxxb2FD6mZqa6vBaeckMZudig=,tag:qCfuMLNwp4tu8R2ImAAM0A==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:qnJqaTo+2sY/sm0+99NPbA==,iv:VeqBUD3cLqcnDY9QrsN/+GdPsvqXWjVVTqVfH84Ggyk=,tag:2WGudTl1sqBtkDNgGeTGjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwc0VQSzNXSWg4Z2V4bXZ3
            REdFdXNVOUtUNXdLc1NZcVFUWnhWL21FRm53CnAyOFBVT3dlNk5tUWpJVldyYzln
            V2ZSdzFIYy9qYnhMK1Z6aWJZdDdENWMKLS0tIGN3c2pVaDVpaFNVYWRMRG84VTRs
            WFhMMDhBZ25aa3RZSFhjYUg2NFdGTUEKjVttWC/BONYIqxPTw8OK9dnauYcebujm
            z9qxtlUIUhHoIdjmpZwh32961YcyupO+DnNjUo65Iy79HxXh1vwojg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T17:39:42Z"
    mac: ENC[AES256_GCM,data:3jidq7LnfJKJmj6dlAXjjH7gRZabubp0uKgQaHeBY1M7rHT7t9ShWeumTaIZKpQffvV8ur7YzavIAAMbiT+MTWov5d6kTHjnVmC5xyludwVFFXBzmCU85Y7YCkBO3XfmsGP+SHcUpunNQ9ie5OIEEmSjUbQJUaXGEJvcm6K7YtM=,iv:EW/kLtiN/nrro73ahpWYF1WbmoJVU+D+rNH4fT6Qmig=,tag:OaKtCQfPQpoBqngQYIbkIQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
