# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: monitoring-secrets
    namespace: monitoring
stringData:
    HOME_ASSISTANT_BEARER: ENC[AES256_GCM,data:bjI+lQV/Pr8WKO06johSS2aeNKTttMACpaWaEbHMu2dZRcIMMXAOtRUisAJD+MxQnAcYHFWOdtJUu752S8mvcYBPBa76dAAc0heYesvj6ucHCyW/yhfsilk9pkruantALOZ/fUif8DBb7PecskWvVgfjNy0r5KH/riUX+wZs2qzdPLnSECi3T1cKJK57FgHnhMogwSEaifr0GB9XkxbYJeD8TriBOI8DRhuQQGo/KTKlongL2LYM,iv:C2Vo8FGKQnCIdhkwqeUOBf+Qyvo+7qgEHILc5FN+vuQ=,tag:SOwR5vEKJU67PT2BM3lUvQ==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:z1y1+89k3EzRheQa0fIwuCZq2viYPRK7LWSzd10GXwtHQWnQ5Wyc2xUuMBYyOS7jZqfXkGMQrvfoKZzsrLvTaoNJXtVMw8Db3LvlmhF8Z9ovZj2GrP15h6SeU+5S7PuS+fVqO4bXnqAG5onJDUO0XkD2J9sxk/MY,iv:bFzGMcrFwFdYrI3HmoEso6sca6JIB+ChdwZ7OrBuqww=,tag:hAKr3djuzp0zWfUGfz93pA==,type:str]
    SECRET_GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:WAez6eeD9v7r6jvc1s3w9w==,iv:ZcGfKHBfWL8kSDfCNrcOqdLFc0/OeB3xL5F8h6bL8zk=,tag:vx5BSVLAcd0/7hv7r15iXw==,type:str]
    SECRET_GRAFANA_ADMIN_USER: ENC[AES256_GCM,data:pfAU0akNSf3x+A==,iv:k2f2/g1BpgGA3x6HInkhEDptqf6nTC/CFyrJXtHAylQ=,tag:by0NipWvHzO8s7PKPjuDkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d1BMT2RlMWpkd1FmRVQ5
            OUJLRCtHMzhhOGMyTTIzMGptQzR3U3g0emdzClRVYldYL0liTHVHMXkzOUxLaXhN
            WVROKytYQ0ppRFV6NlVweFNLOGovWXMKLS0tIGRTbElDZUtPNGJPbmZwekhKMFBS
            N0lTazlCSXdLbHVoc1kveVNWaGhPZXcKOhbIM4rnr6WRxxVPCiTNRZL+bjbgUCb3
            nGhScfp9sY7gfvQZY9Og7EOHY/nZoS66JgZho4qiItgJyDN3mO8dHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T18:05:49Z"
    mac: ENC[AES256_GCM,data:IWo2fdYqMMvCOv6ObsJemQuwP8UqgVuL/vAXUoSNoJkNnLjY5m6JLz7kgPGRkg13/OZoMoNJShxyu6jv0dwxq5ahHrj7o8v4AB16sG3U09GkKX+zW1osbUwBeXdyXGfCIOqnrbkd6Z6ADC5U/b1ZuHGMHRFsTELytjfgPLECces=,iv:DZ1C2X945YolW6x1PkC/DIEogpH4GuAmUQeWV+RLzs8=,tag:NnYGgd74j5sle7OTYhQW8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
