---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: shiori
  name: shiori
  namespace: shiori
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: nfs-client