
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: adguard
spec:
  interval: 5m
  chart:
    spec:
      chart: adguard-home
      version: 0.0.6
      sourceRef:
        kind: HelmRepository
        name: nliakm-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.45
      pullPolicy: IfNotPresent

    # Number of replicas to be deployed
    replicaCount: 1

    services:
      dns:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: "192.168.178.203"
        tcp:
          port: 53
        udp:
          port: 53
    ingress:
      enabled: true
      className: traefik
      hostName: "adguardhome.${SECRET_DOMAIN}"
      PathType: Prefix
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-production
        hajimari.io/enable: "true"
        hajimari.io/icon: shield-check-outline
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
      tls:
        secretName: adguardhome-tls

    resources:
      requests:
        cpu: 125m
        memory: 64Mi
      limits:
        cpu: 250m
        memory: 512Mi

    config:
      http:
        pprof:
          port: 6060
          enabled: false
        address: 0.0.0.0:80
        session_ttl: 720h
      users:
      - name: admin
        password: ${ADGUARD_ADMIN_PASS}
      auth_attempts: 5
      block_auth_min: 15
      http_proxy: ""
      language: ""
      theme: auto
      dns:
        bind_hosts:
          - 0.0.0.0
        port: 53
        anonymize_client_ip: false
        ratelimit: 20
        ratelimit_subnet_len_ipv4: 24
        ratelimit_subnet_len_ipv6: 56
        ratelimit_whitelist: []
        refuse_any: true
        upstream_dns:
          - https://dns10.quad9.net/dns-query
        upstream_dns_file: ""
        bootstrap_dns:
          - 9.9.9.10
          - 149.112.112.10
          - 2620:fe::10
          - 2620:fe::fe:10
        fallback_dns: []
        all_servers: false
        fastest_addr: false
        fastest_timeout: 1s
        allowed_clients: []
        disallowed_clients: []
        blocked_hosts:
          - version.bind
          - id.server
          - hostname.bind
        trusted_proxies:
          - 127.0.0.0/8
          - ::1/128
        cache_size: 4194304
        cache_ttl_min: 0
        cache_ttl_max: 0
        cache_optimistic: false
        bogus_nxdomain: []
        aaaa_disabled: false
        enable_dnssec: false
        edns_client_subnet:
          custom_ip: ""
          enabled: false
          use_custom: false
        max_goroutines: 300
        handle_ddr: true
        ipset: []
        ipset_file: ""
        bootstrap_prefer_ipv6: false
        upstream_timeout: 10s
        private_networks: []
        use_private_ptr_resolvers: true
        local_ptr_upstreams: []
        use_dns64: false
        dns64_prefixes: []
        serve_http3: false
        use_http3_upstreams: false
      tls:
        enabled: true
        server_name: "adguardhome.${SECRET_DOMAIN}"
        force_https: false
        port_https: 443
        port_dns_over_tls: 853
        port_dns_over_quic: 853
        port_dnscrypt: 0
        allow_unencrypted_doh: true
        certificate_path: "/opt/adguardhome/certificates/tls.crt"
        private_key_path: "/opt/adguardhome/certificates/tls.key"
        strict_sni_check: false
      querylog:
        ignored: []
        interval: 2160h
        size_memory: 1000
        enabled: true
        file_enabled: true
      statistics:
        ignored: []
        interval: 24h
        enabled: true
      filters:
        - enabled: true
          url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
          name: AdGuard DNS filter
          id: 1
        - enabled: false
          url: https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
          name: AdAway Default Blocklist
          id: 2
      whitelist_filters: []
      user_rules:
      - "192.168.178.201 monica.${SECRET_DOMAIN}"
      - "192.168.178.201 adguardhome.${SECRET_DOMAIN}"
      - "192.168.178.201 nas.${SECRET_DOMAIN}"
      - "192.168.178.201 alert-manager.${SECRET_DOMAIN}"
      - "192.168.178.201 grafana.${SECRET_DOMAIN}"
      - "192.168.178.201 hass.${SECRET_DOMAIN}"
      - "192.168.178.201 prometheus.${SECRET_DOMAIN}"
      - "192.168.178.201 rezepte.${SECRET_DOMAIN}"
      - "192.168.178.201 traefik.${SECRET_DOMAIN}"
      - "192.168.178.201 start.${SECRET_DOMAIN}"
      - "192.168.178.201 router.${SECRET_DOMAIN}"
      - "192.168.178.201 zwave.${SECRET_DOMAIN}"
      - "192.168.178.201 scraang.${SECRET_DOMAIN}"
      - "192.168.178.201 scraang-dev.${SECRET_DOMAIN}"
      - "192.168.178.201 argocd.${SECRET_DOMAIN}"
      - "192.168.178.201 pihole.${SECRET_DOMAIN}"
      - "192.168.178.201 weave.${SECRET_DOMAIN}"
      - "192.168.178.201 miniflux.${SECRET_DOMAIN}"
      dhcp:
        enabled: false
        interface_name: ""
        local_domain_name: lan
        dhcpv4:
          gateway_ip: ""
          subnet_mask: ""
          range_start: ""
          range_end: ""
          lease_duration: 86400
          icmp_timeout_msec: 1000
          options: []
        dhcpv6:
          range_start: ""
          lease_duration: 86400
          ra_slaac_only: false
          ra_allow_slaac: false
      filtering:
        blocking_ipv4: ""
        blocking_ipv6: ""
        blocked_services:
          schedule:
            time_zone: UTC
          ids: []
        protection_disabled_until: null
        safe_search:
          enabled: false
          bing: true
          duckduckgo: true
          google: true
          pixabay: true
          yandex: true
          youtube: true
        blocking_mode: default
        rewrites: []
        safebrowsing_cache_size: 1048576
        safesearch_cache_size: 1048576
        parental_cache_size: 1048576
        cache_time: 30
        filters_update_interval: 24
        blocked_response_ttl: 10
        filtering_enabled: true
        parental_enabled: false
        safebrowsing_enabled: false
        protection_enabled: true
      clients:
        runtime_sources:
          whois: true
          arp: true
          rdns: true
          dhcp: true
          hosts: true
        persistent: []
      log:
        file: ""
        max_backups: 0
        max_size: 100
        max_age: 3
        compress: false
        local_time: false
        verbose: false
      os:
        group: ""
        user: ""
        rlimit_nofile: 0
      schema_version: 27