---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mondoo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/mondoohq/mondoo-operator
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/