---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://stakater.github.io/stakater-charts
  timeout: 3m
