---
kubernetes:
  children:
    master:
      hosts:
        rpi4k3s1:
          ansible_host: 192.168.178.83
    worker:
      hosts:
        rpi4k3s2:
          ansible_host: 192.168.178.84
        rpi4k3s3:
          ansible_host: 192.168.178.85