{
 "title": "New dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Licht", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Lichterkette",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "light_state{friendly_name=\"Lichterkette\"}"
    }
   ]
  },
  {
   "title": "Wohnzimmerlampe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "light_state{entity=\"light.wohnzimmer\",friendly_name=\"Wohnzimmerlampe\"}"
    }
   ]
  },
  {
   "title": "Sofalampe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "light_state{domain=\"light\",entity=\"light.on_off_plug_1\",friendly_name=\"Sofalampe\"}"
    }
   ]
  },
  {
   "title": "Schlafzimmerlampe",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "light_state{entity=\"light.schlafzimmer\",friendly_name=\"Schlafzimmer\"}"
    }
   ]
  },
  { "title": "Temperatur", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Temperaturen drinnen und draußen",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature_c{entity=~\"(climate.*|sensor.dark_sky_temperature)\"}",
     "legendFormat": "{{ entity }}"
    }
   ]
  },
  {
   "title": "Batteriestände Heizthermostate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "battery_level_percent", "legendFormat": "{{ friendly_name }}" }
   ]
  }
 ]
}