{
 "title": "Hydroponics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Regular Pump",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_input_boolean_state{entity=\"input_boolean.regelmaessiges_pumpen\"}"
    }
   ]
  },
  {
   "title": "Time based Pump",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_input_boolean_state{entity=\"input_boolean.pump_automation\"}"
    }
   ]
  },
  {
   "title": "Time based Pump",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_input_boolean_state{entity=\"input_boolean.pump_automation\"}"
    }
   ]
  },
  {
   "title": "Time based Pump",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_input_boolean_state{entity=\"input_boolean.pump_automation\"}"
    }
   ]
  },
  {
   "title": "Shelly h+t Battery",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_battery_percent{entity=\"sensor.shellyh_t_battery\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{entity=\"sensor.shellyh_t_temperature\"}",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "homeassistant_climate_current_temperature_celsius{entity=\"climate.ts_arbeitszimmer\"}",
     "legendFormat": "Thermostat"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "homeassistant_sensor_humidity_percent{entity=\"sensor.shellyh_t_humidity\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  }
 ]
}