{
 "title": "Synology NAS",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_cpu_utilization_total\"} / 100"
    }
   ]
  },
  {
   "title": "CPU utilization user",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_cpu_utilization_user\"} / 100"
    }
   ]
  },
  {
   "title": "MEM Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_memory_usage_real\"}"
    }
   ]
  },
  {
   "title": "Update available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_update_available\"}"
    }
   ]
  },
  {
   "title": "Security Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_security_status\"}"
    }
   ]
  },
  {
   "title": "Max Bad Sectors exc (D1)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_exceeded_max_bad_sectors\"}"
    }
   ]
  },
  {
   "title": "Max Bad Sectors exc (D2)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_exceeded_max_bad_sectors\"}"
    }
   ]
  },
  {
   "title": "Max Bad Sectors exc (D3)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_exceeded_max_bad_sectors_3\"}"
    }
   ]
  },
  {
   "title": "Max Bad Sectors exc (D4)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_exceeded_max_bad_sectors_4\"}"
    }
   ]
  },
  {
   "title": "Sys Load (5m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_unit_load{entity=\"sensor.synologynas_cpu_load_average_5_min\"})"
    }
   ]
  },
  {
   "title": "Sys Load (15m avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(homeassistant_sensor_unit_load{entity=\"sensor.synologynas_cpu_load_average_15_min\"})"
    }
   ]
  },
  {
   "title": "Volume Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_volume_used\"}"
    }
   ]
  },
  {
   "title": "Below Min Rem. Life (D1)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_below_min_remaining_life\"}"
    }
   ]
  },
  {
   "title": "Below Min Rem. Life (D2)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_below_min_remaining_life_2\"}"
    }
   ]
  },
  {
   "title": "Below Min Rem. Life (D3)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_below_min_remaining_life_3\"}"
    }
   ]
  },
  {
   "title": "Below Min Rem. Life (D4)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_binary_sensor_state{entity=\"binary_sensor.synologynas_below_min_remaining_life_4\"}"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "homeassistant_sensor_temperature_celsius{entity=~\"sensor.synologynas_temperature.*\"}",
     "legendFormat": " "
    }
   ]
  },
  { "title": "Basic CPU / Mem / Net", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_cpu_utilization_total\"}",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_cpu_utilization_user\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Memory basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_percent{entity=\"sensor.synologynas_memory_usage_real\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Download / Upload basic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "homeassistant_sensor_unit_kb_per_s{entity=\"sensor.synologynas_download_throughput\"}",
     "legendFormat": "{{ friendly_name }}"
    },
    {
     "expr": "homeassistant_sensor_unit_kb_per_s{entity=\"sensor.synologynas_upload_throughput\"}",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Used space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dectbytes" } },
   "targets": [
    { "expr": "homeassistant_sensor_unit_tb", "legendFormat": "{{ friendly_name }}" }
   ]
  }
 ]
}