---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-app-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firefly-iii-db-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
