apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
    hajimari.io/enable: "true"
    hajimari.io/icon: "chef-hat"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    ingress.kubernetes.io/custom-frame-options-value: ""
    ingress.kubernetes.io/frame-deny: "false"
  name: recipes
  namespace: default
spec:
  tls:
  - hosts:
     - "*.${SECRET_DOMAIN}"
    secretName: "tls-wildcard-secret"
  rules:
  - host: "rezepte.${SECRET_DOMAIN}"
    http:
      paths:
      - backend:
          service:
            name: recipes
            port:
              number: 8080
        path: /
        pathType: Prefix
      - backend:
          service:
            name: recipes
            port:
              number: 80
        path: /media
        pathType: Prefix
      - backend:
          service:
            name: recipes
            port:
              number: 80
        path: /static
        pathType: Prefix
