apiVersion: k8s.mondoo.com/v1alpha2
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  mondooCredsSecretRef:
    name: mondoo-client
  kubernetesResources:
    enable: true
  nodes:
    enable: true
  admission:
    enable: true
    mode: permissive
    replicas: 1
    certificateProvisioning:
      mode: cert-manager
  scanner:
    replicas: 1