apiVersion: k8s.mondoo.com/v1alpha2
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  mondooTokenSecretRef:
    name: mondoo-token
  mondooCredsSecretRef: 
    name: mondoo-client
  kubernetesResources:
    enable: true
  consoleIntegration:
    enable: true
  nodes:
    enable: true
  admission:
    enable: true
    mode: permissive
    replicas: 1
    serviceAccountName: mondoo-operator-webhook
    certificateProvisioning:
      mode: cert-manager
  scanner:
    serviceAccountName: mondoo-operator-k8s-resources-scanning
    replicas: 1
