apiVersion: v1
kind: Service
metadata:
  name: nas-external
  namespace: networking
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 5000
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: nas-webdav
  namespace: networking
spec:
  ports:
  - name: webdav
    port: 80
    protocol: TCP
    targetPort: 5005
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas-external
  namespace: networking
subsets:
- addresses:
  - ip: ${NFS_SERVER}
  ports:
  - name: app
    port: 5000
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: nas-webdav
  namespace: networking
subsets:
- addresses:
  - ip: ${NFS_SERVER}
  ports:
  - name: webdav
    port: 5005
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nas-ingress
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/appName: "NAS"
    hajimari.io/enable: "true"
    hajimari.io/icon: "nas"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "nas.${SECRET_DOMAIN}"
      secretName: "nas-ingress-tls"
  rules:
    - host: "nas.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nas-external
                port:
                  number: 80
          - path: /webdav
            pathType: Prefix
            backend:
              service:
                name: nas-webdav
                port:
                  number: 80                  
