apiVersion: v1
kind: Service
metadata:
  name: router-external
  namespace: networking
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: router-external
  namespace: networking
subsets:
- addresses:
  - ip: ${GATEWAY_ADDR}
  ports:
  - name: app
    port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-ingress
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/appName: "router"
    hajimari.io/enable: "true"
    hajimari.io/icon: "router-wireless"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "router.${SECRET_DOMAIN}"
      secretName: "router-ingress-tls"
  rules:
    - host: "router.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router-external
                port:
                  number: 80
