apiVersion: v1
kind: Service
metadata:
  name: zwave-external
  namespace: networking
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8091
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: zwave-external
  namespace: networking
subsets:
- addresses:
  - ip: ${PIHOLE_SERVER}
  ports:
  - name: app
    port: 8091
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zwave-ingress
  namespace: networking
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    hajimari.io/appName: "zwave control"
    hajimari.io/enable: "true"
    hajimari.io/icon: "z-wave"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
spec:
  ingressClassName: "traefik"
  tls:
    - hosts:
        - "zwave.${SECRET_DOMAIN}"
      secretName: "zwave-ingress-tls"
  rules:
    - host: "zwave.${SECRET_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zwave-external
                port:
                  number: 80
