apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    METALLB_LB_RANGE: ENC[AES256_GCM,data:qePFYtbYnHRTCjW6RqRyEXn8MX+h2y4FuGdgYDeDxQ==,iv:butg3rR4dgV+nelZoR21+T990QYtVZ+b0UZq/zKDEJg=,tag:KVaa5/FikhlqDpDDKv/zsg==,type:str]
    METALLB_TRAEFIK_ADDR: ENC[AES256_GCM,data:xIUGxpR/CMcEixunoE13,iv:AKRUnHne963gTE+NrWqgVXsBOo+pq5VfgJSxMOGu548=,tag:0BpXV2QUfsSeArYwCpmtWA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwRzVKVFhKd1BwTkk0bWdV
            TUdxZWYzTkhUVTZ3NWN2YUc0d1NacWpwOEdzCmU5emZWN2NQTE1yVGtNd1ZZMUpS
            WGtoQzRhWEJURzBrUGZXajV6Wm1XMm8KLS0tIEc5UjlNdXZOeGFjV1M2WGg1ck9O
            cytmcmR1eXRaK1lRRjB5M0tsczJpS28KRlVn1ijm0hCY6GEsIsPE3YJoiZcODriH
            prL6Z/NuwTgST5nmLuBfZmj42pipW++0mGR11/wp3TUQwAE1+HB4gA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-04T15:29:40Z"
    mac: ENC[AES256_GCM,data:95SvZlNfbAMXNp+H4iVSUj2MZg5G/9L1SoDz6PeN5O6aFKwOd1IHJ1QOV8czAhAw9Ft5nMrFdwhptle+qpbXXtCIht2yTbXT7n6fgb63aL8FcTAGFW0LnpeCI2m2bzbueiTWIi3vCOi7Qnrf801IvyTsG8Duxs8lHcdeUGENhRc=,iv:0iHEaKQdRIyobhDsaC4GRun6hea4tcrv1h8rgkNWhXw=,tag:YR7yEtj/naulSxC7D84u5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
