# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secrets
    namespace: miniflux
stringData:
    username: ENC[AES256_GCM,data:oEzI3ZR/tGCE+1Bw4A==,iv:4KKSykBnC50XlQik1oU8VxPfTHfQBqV7eA38Po69ZoA=,tag:2UlocObg+S3T7JtRnjz8BA==,type:str]
    password: ENC[AES256_GCM,data:ZVx1dM1aXqtNzKnbQgIy5cbcN5adCn48,iv:ev+nM/VJSGsahPncMcXiNLFsmLr/lZqBOeZeGVaDjTQ=,tag:pb+c97XY2v7CRePbVQ8ELQ==,type:str]
    base_url: ENC[AES256_GCM,data:FKBsVoRiiwdh6VfFx4ejMwJ0dseVL22t,iv:1Esx73NFC7yeXTNtipCM7ggIQ2v0tiwUcMvDlLzM6oU=,tag:gVs2XX8WlP3iiLHJF44Rnw==,type:str]
    postgres_password: ENC[AES256_GCM,data:wqPibD3zcMH4phNjAXObMLL5TZbaWVk=,iv:Ih1WbTqPWRWjpeNpKMVsZH7C1x48aENbeaUYr/p+a0M=,tag:GuI0RVSWxbr6lBHYpShBCw==,type:str]
    database_url: ENC[AES256_GCM,data:DerU2ypCV2Y2WAuNem3bRiqIB6rM7M/ULUEglMe8/n39ZockKkHsS0SAcJM/+u3OzphAYWKTupam2ffhD90DxZ/UpoNLhwaOuiOWvmqMy4ZEHQrALD9K/g==,iv:UNcKgiu2wz84hApJorZ6APG4Amc/FpDnqMrQE1+i474=,tag:U5w+Wym85KF6y64cGy6Eiw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvL0dnTmwvZFpkaUlJMlJL
            SlkxMVlOREtVQURRNkV4ZTlRTm91WEc3Y0ZZCnVyekp1cG9NR3FDMjhlQTl6ZVJL
            eTdzb1R2Nk5DV1BsVkErYkhRSWU2UWcKLS0tIFJkRjRFaFp5YlBmeDRPSXQ0aXkx
            TGxlS0V6Z3l3RlZKekNETm5RNFFVemMKYy3OiQ/4ZH2ByNLHr0VwC/ZNVoOeZakS
            MTirz2G5u43PEe2qHJLTUbCtop3WKxjx1qIiKLciGiPlwbGMGE8cWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-13T14:50:31Z"
    mac: ENC[AES256_GCM,data:ciEqInjMBCFhMYka51RNyCdSz+nariE5EKdpmDNzfprsABat6PCBJgWUAmLPQBSJPl595cX5z8AmDjdMt64/LGFnrsk5KqtSr674KmuATFKbPPPwv/EVB7eTr7wXssGlCUw49Sz/kPwPPMAZ8IIImp17Py2A09GAan8a+NfPo/g=,iv:qphDmFC9Rs/H0BnSmBfgSTd42yHHw43WyusPd8adKJA=,tag:3EroSJLgqkXO+/9OyW8y3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
