---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      version: 21.0.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system      
  values:
    fullnameOverride: prometheus
#    defaultRules:
#      create: true
#      rules:
#        alertmanager: true
#        etcd: false
#        general: true
#        k8s: true
#        kubeApiserver: true
#        kubeApiserverAvailability: true
#        kubeApiserverError: true
#        kubeApiserverSlos: true
#        kubelet: true
#        kubePrometheusGeneral: true
#        kubePrometheusNodeAlerting: true
#        kubePrometheusNodeRecording: true
#        kubernetesAbsent: true
#        kubernetesApps: true
#        kubernetesResources: true
#        kubernetesStorage: true
#        kubernetesSystem: true
#        kubeScheduler: true
#        kubeStateMetrics: true
#        network: true
#        node: true
#        prometheus: true
#        prometheusOperator: true
#        time: true
    additionalPrometheusRulesMap:
      rule-name:
        groups:
          - name: home-assistant
            rules:
              - alert: BatteryLow
                expr: battery_level_percent < 3
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: Battery low for entity {{ $labels.friendly_name }}
                  description: "An entity is low on battery\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
              - alert: RsyncFailed
                expr: rsync_exit_code != 0
                for: 5m
                labels:
                  severity: critical
                annotations:
                  summary: Last rsync job failed
                  description: |-
                    "Rsync job (interval: {{ $labels.interval }}, directory: {{ $labels.directory }}) failed for instance {{ $labels.instance }} with exit code {{ $value }}."
              - alert: PrometheusTargetMissing
                expr: up == 0
                for: 0m
                labels:
                  severity: critical
                annotations:
                  summary: Prometheus target missing (instance {{ $labels.instance }})
                  description: "A Prometheus target has disappeared. An exporter might be crashed.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
              - alert: NASSecurityStatus
                expr: binary_sensor_state{job="home-assistant",entity="binary_sensor.synologynas_security_status"} != 0
                for: 0m
                labels:
                  severity: warning
                annotations:
                  summary: NAS has atleast one security warning
                  description: "There are security warnings on the NAS to check.\nThese can be outdated packages or unsecure settings."
              - alert: NASUpdateInformation
                expr: binary_sensor_state{job="home-assistant",entity="binary_sensor.synologynas_update_available"} != 0
                for: 0m
                labels:
                  severity: warning
                annotations:
                  summary: NAS update available
                  description: "The NAS has a new update available."
              - alert: NASMaxBadSectors
                expr: binary_sensor_state{domain="binary_sensor",entity=~".*exceeded_max_bad_sectors"} != 0
                for: 0m
                labels:
                  severity: critical
                annotations:
                  summary: Hard disk exceeded max bad sectors
                  description: |-
                    {{ $labels.friendly_name }}. 
                    Actions to take: https://kb.synology.com/en-global/DSM/tutorial/How_to_diagnose_drives_health_status_when_receiving_bad_sector_warning
    alertmanager:
      enabled: true
      config:
        global:
          resolve_timeout: 5m
        receivers:
          - name: "discord_webhook"
            webhook_configs:
              - url: "http://alertmanager-discord:9094"
                send_resolved: true
          - name: 'null'
        route:
          group_by: ["alertname", "job"]
          group_wait: 30s
          group_interval: 5m
          repeat_interval: 110h
          receiver: "discord_webhook"
          routes:
            - matchers: [alertname="Watchdog"]
              receiver: 'null'
            - matchers: [severity=~"(critical|warning|error)"]
              receiver: 'discord_webhook'
              continue: true
        inhibit_rules:
          - source_matchers: [severity="critical"]
            target_matchers: [severity="warning"]
            equal: ["alertname", "namespace"]
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
          cert-manager.io/private-key-secret-name: "root-secret"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Alertmanager"
          hajimari.io/group: "monitoring"
          hajimari.io/icon: "email-alert"
        hosts:
          - "alert-manager.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "alert-manager.${SECRET_DOMAIN}"
            secretName: "alert-manager-tls-secret"
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              storageClassName: "nfs-client"
              resources:
                requests:
                  storage: 1Gi
    kubeScheduler:
      enabled: false
    kubeControllerManager:
      enabled: false
    nodeExporter:
      serviceMonitor:
        relabelings:
          - action: replace
            regex: (.*)
            replacement: $1
            sourceLabels:
              - __meta_kubernetes_pod_node_name
            targetLabel: kubernetes_node
    kube-state-metrics:
      fullnameOverride: kube-state-metrics
    prometheus-node-exporter:
      fullnameOverride: node-exporter
    grafana:
      enabled: false
      forceDeployDashboards: true
      sidecar:
        dashboards:
          multicluster:
            etcd:
              enabled: true
    # Setting this option to 0 disabled CPU limits
    prometheusOperator:
      configReloaderCpu: 0
    # prometheusConfigReloader:
    #   # image to use for config and rule reloading
    #   image:
    #     repository: quay.io/prometheus-operator/prometheus-config-reloader
    #     tag: v0.52.0
    #   # resource config for prometheusConfigReloader
    #   resources:
    #     requests:
    #       cpu: 100m
    #       memory: 50Mi
    #     limits:
    #       cpu: 800m
    #       memory: 1Gi      
    prometheus:
      ingress:
        enabled: true
        pathType: Prefix
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
          cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
          cert-manager.io/private-key-secret-name: "root-secret"
          hajimari.io/enable: "true"
          hajimari.io/appName: "Prometheus"
          hajimari.io/group: "monitoring"
          hajimari.io/icon: "torch"
        hosts:
          - "prometheus.${SECRET_DOMAIN}"
        tls:
          - hosts:
              - "prometheus.${SECRET_DOMAIN}"
            secretName: "prometheus-tls-secret"
      thanosService:
        enabled: false
      thanosServiceMonitor:
        enabled: false
      prometheusSpec:
        replicas: 1
        replicaExternalLabelName: "replica"
        ruleSelectorNilUsesHelmValues: false
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
        retention: 30d
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 1Gi
            cpu: 1500m
        enableAdminAPI: true
        walCompression: true
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: "nfs-client"
              resources:
                requests:
                  storage: 10Gi
        additionalScrapeConfigs:
          - job_name: "home-assistant"
            scheme: http
            metrics_path: /api/prometheus
            tls_config:
              insecure_skip_verify: true
            authorization:
              type: Bearer
              credentials: "${HOME_ASSISTANT_BEARER}"
            static_configs:
              - targets:
                - "${HOME_ASSISTANT_SERVER}:8123"
          - job_name: "node-exporter"
            honor_timestamps: true
            static_configs:
              - targets:
                  - "${PIHOLE_SERVER}:9100"
                  - "${HOME_ASSISTANT_SERVER}:9100"
