---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rocketchat
  namespace: rocketchat
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://rocketchat.github.io/helm-charts
      chart: rocketchat
      version: 6.2.10
      sourceRef:
        kind: HelmRepository
        name: rocketchat-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system
  values:
    mongodb:
      persistence:
        enabled: true
        ## mongodb data Persistent Volume Storage Class
        ## If defined, storageClassName: <storageClass>
        ## If set to "-", storageClassName: "", which disables dynamic provisioning
        ## If undefined (the default) or set to null, no storageClassName spec is
        ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
        ##   GKE, AWS & OpenStack)
        ##
        storageClass: "nfs-client"
        accessMode: ReadWriteOnce
        size: 1Gi

      volumePermissions: { enabled: true }

    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 300m

    ## Configure the ingress object to hook into existing infastructure
    ### ref : http://kubernetes.io/docs/user-guide/ingress/
    ###
    ingress:
      enabled: true
      ingressClassName: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        cert-manager.io/private-key-secret-name: "root-secret"
      path: /
      pathType: Prefix
      hosts:
        - "rocketchat.${SECRET_DOMAIN}"       
      tls:
        - hosts:
          - "rocketchat.${SECRET_DOMAIN}"
          secretName: "rocketchat-tls-secret"
