---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scraang-www
  namespace: default
  labels:
    app: scraang  
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Mi
