---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 5m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  dependsOn:
    - name: nfs-subdir-external-provisioner
      namespace: nfs-system
  values:
    image:
      registry: docker.io
      repository: bitnami/postgresql
      tag: 14.9.0
    global:
      postgresql:
        auth:
          username: test
          database: test
          existingSecret: "postgresql-credentials"
          secretKeys:
            adminPasswordKey: "postgres-password"
            userPasswordKey: "user-password"
      primary:
        resources:
          requests:
            cpu: 15m
            memory: 50Mi
          limits:
            memory: 200Mi
        persistence:
          size: 10Gi
          storageClass: "nfs-client"
        initdb:
          scriptsSecret: "initdb-script"
