---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencript-wildcard-cert
  namespace: default
spec:
  secretName: tls-wildcard-secret
  issuerRef: 
    kind: ClusterIssuer
    name: letsencrypt-production
  dnsNames:
    - "*.${SECRET_DOMAIN}"
