# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1hra9lsurxkx96y9vgckl38ct3x4nkq655nnmfpe2xly93kqypqps0yhwmc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1U3FnUHB3MWswaG1adGU4
            MUpKWnovNnZCcFJWZEt0MGMrRUFaL2JjT3hzCnl2a243N0FnRVB1aEZCcmZ3eWdi
            Z3daeVV3cFNJRUJyRzR0cHprb3dCTWcKLS0tIEJmWUZCS1lVc2lUWWpia0NzQ05N
            eXNBaGp5V0dsQ1pLakprU0NnM3dEOTAKG46YVAGaWce9VvZscmEJQ10gi3DT37sS
            LMyiRQA7KuQ1tAQkEjWseh4PB9sF1IDAUeXJNVZYEmaiIIpxGN7a9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-11-26T22:30:00Z"
    mac: ENC[AES256_GCM,data:vkab1Hy1B9jSN1/Ys/lULLpXd1K9b0n4a33Yw1TxjbbDaECf3cTmc+Zqr+Jr1crg3ApMXz2XBiiPsqkhDKib1sFW8igRDs2wMbuMU3knQQxCMSdq7fteObSgdhnDCvSemqR9l/4C0n10rU19pEewp2enZND64kIkBY5DGOkxeDc=,iv:xD6bS6/+Fign9td9IwdgyBDpCgKzivAT0afwaNm7MVY=,tag:PcDq6yFgqqUqlLrxC9TW7g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
