---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  secretName: root-secret
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: k3s.fritz.box
  organization:
  - FRITZ.BOS
  dnsNames:
  - start.fritz.box
  - grafana.fritz.box
  - prometheus.fritz.box
  - alert-manager.fritz.box
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io