---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: osm-system
  secretName: selfsigned-ca
  issuerRef:
    name: selfsigned-cluster-issue
    kind: ClusterIssuer
    group: cert-manager.io