apiVersion: v1
kind: Service
metadata:
  name: alertmanager-discord
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager-discord
spec:
  selector:
    app.kubernetes.io/name: alertmanager-discord
  ports:
    - name: http
      protocol: TCP
      port: 9094
      targetPort: http
  type: ClusterIP