apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: alertmanager
  namespace: flux-system
spec:
  type: alertmanager
  # webhook address (ignored if secretRef is specified)
  address: http://prometheus-alertmanager:9093/api/v2/alerts/"